import express from "express";
import {
  createFB,
  getFB,
  getOneFB,
  updateFb,
} from "../controllers/foodbank.js";
//the express router
const router = express.Router();

/**
 * @swagger
 * components:
 *   schemas:
 *    Foodbank:
 *     type: object
 *     required:
 *     - fbName
 *     - fbDescription
 *     - fbAddress
 *    properties:
 *      id:
 *        type: string
 *        description: The id auto-generated by mongoDB
 *      fbName:
 *        type: string
 *        description: The name of the food bank
 *      fbDescription:
 *        type: string
 *        description: The description of the food bank
 *      fbAddress:
 *        type: string
 *        description: The address of the food bank
 *      fbPic:
 *        type: string
 *        description: The picture of the food bank
 *    example:
 *     id: 62123123
 *     fbName: "Food Bank"
 *     fbDescription: "This is a food bank"
 *     fbAddress: "0xfe8Bcc33f0B5287d24FD1E3e40B058b74fd2924b"
 *     fbPic: "data:image/jpeg;base64..."
 */
//Foodbank get routes
router.get("/getfb", getFB);
router.get("/getonefb/:address", getOneFB);

//Foodbank post routes
router.post("/createfb", createFB);
router.post("/updatefb", updateFb);

export default router;
